---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core.git
    mount_core: https://github.com/puppetlabs/puppetlabs-mount_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    systemd: https://github.com/camptocamp/puppet-systemd.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
